// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmDpMSMX1VWtNA9Ofw9rZU3w5Epwe2hCg',
    appId: '1:238909171496:web:adbac37b1e7c2f5aa8121d',
    messagingSenderId: '238909171496',
    projectId: 'test-project-818f6',
    authDomain: 'test-project-818f6.firebaseapp.com',
    storageBucket: 'test-project-818f6.appspot.com',
    measurementId: 'G-YGF6LPE32H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVyY5A1AFh9JovDKcVwccwvR5FfBXgbd0',
    appId: '1:238909171496:android:8e626842ca7c5b5ca8121d',
    messagingSenderId: '238909171496',
    projectId: 'test-project-818f6',
    storageBucket: 'test-project-818f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLA_nr9MNwcanClMAGMA9VOAq73N8LieE',
    appId: '1:238909171496:ios:db3a5746d103e660a8121d',
    messagingSenderId: '238909171496',
    projectId: 'test-project-818f6',
    storageBucket: 'test-project-818f6.appspot.com',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLA_nr9MNwcanClMAGMA9VOAq73N8LieE',
    appId: '1:238909171496:ios:820fce814344eb79a8121d',
    messagingSenderId: '238909171496',
    projectId: 'test-project-818f6',
    storageBucket: 'test-project-818f6.appspot.com',
    iosBundleId: 'com.example.graduationProject.RunnerTests',
  );
}
